import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import worker,{CODES,hash} from '../stats/worker.mjs';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../stats/migrations/0001_results.sql',import.meta.url),'utf8'));
const env={ADMIN_TOKEN:'test-only-very-long-random-secret-123456789',ALLOWED_ORIGINS:'https://evelyn-codes.github.io',DB:{prepare(sql){return {bind(...args){return {async run(){return db.prepare(sql).run(...args)}}},async all(){return {results:db.prepare(sql).all()}}}}}};
const id='550e8400-e29b-41d4-a716-446655440000';
const post=(result,installationId=id,extra={})=>worker.fetch(new Request('https://stats.example/api/personality-result',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://evelyn-codes.github.io'},body:JSON.stringify({installationId,result,...extra})}),env);
const stats=(token=env.ADMIN_TOKEN)=>worker.fetch(new Request('https://stats.example/api/admin/personality-stats',{headers:{Authorization:'Bearer '+token}}),env);
let d=await (await stats()).json();assert.equal(d.total,0);assert.equal(d.results.length,18);assert.ok(d.results.every(r=>r.count===0&&r.percentage===0));
assert.equal((await stats('bad')).status,401);
assert.equal((await post('LOADING')).status,200);
await Promise.all(Array.from({length:20},()=>post('LOADING')));d=await(await stats()).json();assert.equal(d.total,1);assert.equal(d.results[0].count,1);assert.equal(d.results[0].percentage,100);
const first=db.prepare('SELECT * FROM personality_results').get();assert.equal(first.device_key,await hash(id));assert.ok(!JSON.stringify(first).includes(id));
await post('TBD');d=await(await stats()).json();assert.equal(d.total,1);assert.equal(d.results.find(r=>r.result==='LOADING').count,0);assert.equal(d.results[0].result,'TBD');assert.equal(db.prepare('SELECT created_at FROM personality_results').get().created_at,first.created_at);
await post('ECO','650e8400-e29b-41d4-a716-446655440000');d=await(await stats()).json();assert.equal(d.total,2);assert.equal(d.results[0].percentage,50);
for(const result of ['ABC','TEST',undefined,null,1])assert.equal((await post(result)).status,400);
assert.equal((await post('ECO','bad')).status,400);assert.equal((await post('ECO',id,{answers:[1]})).status,400);
assert.throws(()=>db.prepare('INSERT INTO personality_results(device_key,result_code) VALUES (?,?)').run(first.device_key,'ECO'));
assert.throws(()=>db.prepare('INSERT INTO personality_results(device_key,result_code) VALUES (?,?)').run('x'.repeat(64),'ABC'));
const wrongOrigin=await worker.fetch(new Request('https://stats.example/api/personality-result',{method:'POST',headers:{Origin:'https://evil.example'}}),env);assert.equal(wrongOrigin.status,403);
const noSecret=await worker.fetch(new Request('https://stats.example/api/admin/personality-stats'),{...env,ADMIN_TOKEN:''});assert.equal(noSecret.status,503);
assert.deepEqual(db.prepare('PRAGMA table_info(personality_results)').all().map(r=>r.name),['id','device_key','result_code','created_at','updated_at']);
assert.equal(CODES.length,18);
console.log('PASS: real SQLite unique/upsert; concurrent duplicate submissions; result replacement; all 18 counts; auth; invalid input; data minimization.');
